# Generated by Django 2.2.1 on 2019-05-22 17:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The common name of this community service', max_length=200, null=True)),
                ('parent_organisation', models.CharField(help_text='The parent organisation that delivers this community service', max_length=200, null=True)),
                ('description', models.CharField(help_text='Describe this community service in a short paragraph', max_length=500, null=True)),
                ('url', models.URLField(blank=True, help_text='The website or webpage where this service can be booked, or where more info can be found about it', null=True)),
                ('contact_name', models.CharField(blank=True, help_text='The email address for this ', max_length=100, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='The contact phone number for this community service ', max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, help_text='The contact email address for this community service', max_length=100, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Give a value for how much this community service costs per session/activity. If a simple price cannot be given, leave the field blank.', max_digits=6, null=True)),
                ('days', models.ManyToManyField(to='communityassets.Days')),
            ],
        ),
    ]
