# Generated by Django 2.2.1 on 2019-05-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityassets', '0002_auto_20190519_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityasset',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Give a value for how much this community asset costs per session/activity. If a simple price cannot be given, leave the field blank.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='communityasset',
            name='description',
            field=models.CharField(help_text='Describe this community asset in a short paragraph', max_length=500, null=True),
        ),
    ]
