# Generated by Django 2.2.1 on 2019-05-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communityassets', '0002_auto_20190522_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityasset',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='communityasset',
            name='days',
        ),
        migrations.DeleteModel(
            name='Days',
        ),
    ]
