# Generated by Django 2.2.1 on 2019-05-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityassets', '0003_auto_20190522_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='communityasset',
            name='category',
            field=models.CharField(help_text='Choose a category for this community service', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='communityasset',
            name='description',
            field=models.TextField(help_text='Describe this community service in a short paragraph', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='communityasset',
            name='days',
            field=models.ManyToManyField(to='communityassets.Days'),
        ),
    ]
