# Generated by Django 2.2.1 on 2019-05-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityassets', '0003_auto_20190522_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityasset',
            name='title',
        ),
        migrations.AddField(
            model_name='communityasset',
            name='email',
            field=models.EmailField(blank=True, help_text='The email address for this ', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='communityasset',
            name='name',
            field=models.CharField(help_text='The common name of this community service', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='communityasset',
            name='parent_organisation',
            field=models.CharField(help_text='The parent organisation that delivers this community service', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='communityasset',
            name='url',
            field=models.URLField(blank=True, help_text='The website or webpage where this service can be booked, or where more info can be found about it', null=True),
        ),
        migrations.AlterField(
            model_name='communityasset',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Give a value for how much this community service costs per session/activity. If a simple price cannot be given, leave the field blank.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='communityasset',
            name='description',
            field=models.CharField(help_text='Describe this community service in a short paragraph', max_length=500, null=True),
        ),
    ]
