# Generated by Django 2.2.1 on 2019-05-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityassets', '0004_auto_20190522_1739'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keywords',
        ),
        migrations.RemoveField(
            model_name='communityasset',
            name='category',
        ),
        migrations.RemoveField(
            model_name='communityasset',
            name='days',
        ),
        migrations.AddField(
            model_name='communityasset',
            name='days',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Days',
        ),
    ]
