# Generated by Django 2.2.1 on 2019-05-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityassets', '0004_auto_20190522_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='communityasset',
            name='contact_name',
            field=models.CharField(blank=True, help_text='The email address for this ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='communityasset',
            name='phone',
            field=models.IntegerField(blank=True, help_text='The contact phone number for this community service ', null=True),
        ),
        migrations.AlterField(
            model_name='communityasset',
            name='email',
            field=models.EmailField(blank=True, help_text='The contact email address for this community service', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='communityasset',
            name='days',
            field=models.ManyToManyField(to='communityassets.Days'),
        ),
    ]
