# Generated by Django 2.2.1 on 2019-05-22 17:10

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('communityassets', '0005_auto_20190522_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityasset',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='The contact phone number for this community service ', max_length=128, null=True, region=None),
        ),
    ]
