# Generated by Django 2.2.1 on 2019-05-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communityassets', '0005_auto_20190522_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityasset',
            name='days',
        ),
    ]
