# Generated by Django 2.2.1 on 2019-05-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityassets', '0006_remove_communityasset_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityasset',
            name='category',
            field=models.CharField(blank=True, choices=[('test', 'Test'), ('test1', 'Test1')], max_length=100, null=True),
        ),
    ]
