# Generated by Django 2.2.1 on 2019-05-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityassets', '0008_auto_20190522_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='communityasset',
            name='days',
            field=models.ManyToManyField(blank=True, null=True, to='communityassets.Days'),
        ),
    ]
