# Generated by Django 2.2.1 on 2019-05-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityassets', '0017_auto_20190526_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityasset',
            name='venue',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
