# Generated by Django 2.2.1 on 2019-05-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityassets', '0018_auto_20190526_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityasset',
            name='phone',
            field=models.CharField(blank=True, help_text='Give a contact telephone number, with no spaces', max_length=100, null=True),
        ),
    ]
