# Generated by Django 2.2.1 on 2019-05-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityassets', '0021_auto_20190526_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityasset',
            name='last_updated',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='communityasset',
            name='review_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
