# Generated by Django 2.2.1 on 2019-05-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityassets', '0022_auto_20190526_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityasset',
            name='formatted_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='communityasset',
            name='latlng_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
