# Generated by Django 2.2.1 on 2019-05-27 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communityassets', '0023_auto_20190527_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityasset',
            old_name='formatted_address',
            new_name='lat_lng',
        ),
        migrations.RemoveField(
            model_name='communityasset',
            name='latlng_address',
        ),
    ]
