# Generated by Django 2.2.1 on 2019-06-01 22:01

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('genericcontent', '0002_auto_20190601_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericcontent',
            name='content',
            field=wagtail.core.fields.StreamField([('rich_text', streams.blocks.RichTextBlock()), ('person_profile', wagtail.core.blocks.StructBlock([('image', streams.blocks.APIFriendlyImageChooserBlock(help_text='A headshot of the person', required=True)), ('headline', wagtail.core.blocks.CharBlock(help_text="A positive headline for this story, including the person's first name", max_length=200, required=True)), ('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], help_text='Aim for three short paragraphs: problem, action, result', max_length=1500, required=True))])), ('call_to_action', wagtail.core.blocks.StructBlock([('button_text', wagtail.core.blocks.CharBlock(help_text='The text displayed on the button. Should be three words or less.', max_length=200, required=True)), ('url', wagtail.core.blocks.CharBlock(help_text='The URL the button links to', max_length=200, required=True))])), ('financial_help_checker', wagtail.core.blocks.StructBlock([]))], blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExternalLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('summary', models.CharField(max_length=200, null=True)),
                ('link_text', models.CharField(max_length=400, null=True)),
                ('url', models.URLField(null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='genericcontent.GenericContent')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
