# Generated by Django 2.2.1 on 2019-06-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericcontent', '0004_auto_20190601_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallinks',
            name='popularAdvice',
            field=models.BooleanField(help_text='Show this page as popular advice on the homepage?', null=True),
        ),
        migrations.AddField(
            model_name='externallinks',
            name='popularSearch',
            field=models.BooleanField(help_text='Show this page as a popular search on the homepage?', null=True),
        ),
    ]
