# Generated by Django 2.2.1 on 2019-06-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericcontent', '0005_auto_20190601_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externallinks',
            name='popularAdvice',
        ),
        migrations.RemoveField(
            model_name='externallinks',
            name='popularSearch',
        ),
        migrations.AddField(
            model_name='genericcontent',
            name='popular_advice',
            field=models.BooleanField(help_text='Show this page as popular advice on the homepage?', null=True),
        ),
        migrations.AddField(
            model_name='genericcontent',
            name='popular_search',
            field=models.BooleanField(help_text='Show this page as a popular search on the homepage?', null=True),
        ),
    ]
