# Generated by Django 2.2.1 on 2019-06-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericcontent', '0006_auto_20190601_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericcontent',
            name='popular_advice',
            field=models.BooleanField(blank=True, help_text='Show this page as popular advice on the homepage?', null=True),
        ),
        migrations.AlterField(
            model_name='genericcontent',
            name='popular_search',
            field=models.BooleanField(blank=True, help_text='Show this page as a popular search on the homepage?', null=True),
        ),
    ]
