# Generated by Django 2.2.1 on 2019-06-02 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('genericcontent', '0007_auto_20190601_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericcontent',
            name='image',
            field=models.ForeignKey(blank=True, help_text='A mood-setting image which appears on the homepage and in search results', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
