# Generated by Django 2.2.1 on 2019-05-18 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190518_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='A large, mood-setting image which fills the top of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro',
            field=models.CharField(help_text='Appears under the title', max_length=400, null=True),
        ),
    ]
