# Generated by Django 2.2.1 on 2019-06-02 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_popularadvice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularadvice',
            name='popular_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
