# Generated by Django 2.2.1 on 2019-06-02 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190602_1757'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopularAdvice',
        ),
    ]
