# Generated by Django 2.2.1 on 2019-06-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeevents', '0005_auto_20190522_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifeeventpage',
            name='homepage_summary',
            field=models.CharField(help_text='Appears on the homepage', max_length=400, null=True),
        ),
    ]
