# Generated by Django 2.2.1 on 2019-06-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeevents', '0006_lifeeventpage_homepage_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifeeventpage',
            name='first_paragraph',
        ),
        migrations.RemoveField(
            model_name='lifeeventpage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='lifeeventpage',
            name='homepage_summary',
        ),
        migrations.AddField(
            model_name='lifeeventpage',
            name='intro',
            field=models.CharField(help_text='Appears under the title', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='lifeeventpage',
            name='summary',
            field=models.CharField(help_text='A short summary of the page that appears on the homepage and in search results', max_length=200, null=True),
        ),
    ]
