# Generated by Django 2.2.1 on 2019-06-01 21:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lifeevents', '0007_auto_20190601_2103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LifeEventPage',
            new_name='LifeEvent',
        ),
        migrations.AlterModelOptions(
            name='lifeevent',
            options={},
        ),
    ]
