# Generated by Django 2.2.1 on 2019-06-01 21:35

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lifeevents', '0008_auto_20190601_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeevent',
            name='content',
            field=wagtail.core.fields.StreamField([('rich_text', streams.blocks.RichTextBlock()), ('person_profile', wagtail.core.blocks.StructBlock([('image', streams.blocks.APIFriendlyImageChooserBlock(help_text='A headshot of the person', required=True)), ('headline', wagtail.core.blocks.CharBlock(help_text="A positive headline for this story, including the person's first name", max_length=200, required=True)), ('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], help_text='Aim for three short paragraphs: problem, action, result', max_length=1500, required=True))]))], blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExternalLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('summary', models.CharField(max_length=200, null=True)),
                ('url', models.URLField(max_length=400, null=True)),
                ('link_title', models.URLField(null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='lifeevents.LifeEvent')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
