# Generated by Django 2.2.1 on 2019-06-01 21:48

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lifeevents', '0009_auto_20190601_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externallinks',
            name='link_title',
        ),
        migrations.AddField(
            model_name='externallinks',
            name='link_text',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='externallinks',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='lifeevents.LifeEvent'),
        ),
        migrations.AlterField(
            model_name='externallinks',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
