# Generated by Django 2.2.1 on 2019-06-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifeevents', '0015_genericcontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearnMore',
        ),
    ]
