# Generated by Django 2.2.1 on 2019-06-02 18:57

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('lifeevents', '0016_delete_learnmore'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('summary', models.CharField(help_text='A short summary of the page that appears on the homepage and in search results', max_length=200, null=True)),
                ('intro', models.CharField(help_text='Appears under the title', max_length=400, null=True)),
                ('content', wagtail.core.fields.StreamField([('rich_text', streams.blocks.RichTextBlock()), ('person_profile', wagtail.core.blocks.StructBlock([('image', streams.blocks.APIFriendlyImageChooserBlock(help_text='A headshot of the person', required=True)), ('headline', wagtail.core.blocks.CharBlock(help_text="A positive headline for this story, including the person's first name", max_length=200, required=True)), ('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], help_text='Aim for three short paragraphs: problem, action, result', max_length=1500, required=True))])), ('call_to_action', wagtail.core.blocks.StructBlock([('button_text', wagtail.core.blocks.CharBlock(help_text='The text displayed on the button. Should be three words or less.', max_length=200, required=True)), ('url', wagtail.core.blocks.CharBlock(help_text='The URL the button links to', max_length=200, required=True))])), ('financial_help_checker', streams.blocks.FinancialHelpChecker()), ('needs_explorer', streams.blocks.NeedsExplorer())], blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='lifeevent',
            name='page_ptr',
        ),
        migrations.AlterField(
            model_name='externallinks',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='lifeevents.GenericContentPage'),
        ),
        migrations.DeleteModel(
            name='GenericContent',
        ),
        migrations.DeleteModel(
            name='LifeEvent',
        ),
    ]
