# Generated by Django 2.2.1 on 2019-06-02 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifeevents', '0017_auto_20190602_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeEventPage',
            fields=[
                ('genericcontentpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lifeevents.GenericContentPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('lifeevents.genericcontentpage',),
        ),
    ]
