# Generated by Django 2.2.1 on 2019-06-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeevents', '0018_lifeeventpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericcontentpage',
            name='popular',
            field=models.BooleanField(help_text='Show in the Popular advice section on the homepage', null=True),
        ),
    ]
